name: AWS Startup Community Conference 2022　Call for Papers 応募フォーム
description: AWS Startup Community Conference 2022 Call for Papers へのご応募をご検討頂きありがとうございます。下記のフォームに必要事項をご記入の上、Submitしてください。
title: "<セッションタイトルを最大40文字程度で記入してください>"
labels: [cfp]
assignees:
  - kzk-maeda
body:
  - type: checkboxes
    id: terms
    attributes:
      label: AWS 行動規範 (Code of Conduct) への同意 (必須)
      description: セッションの応募にはイベント登録規約、および AWS 行動規範 Code of Conduct への同意が必要です
      options:
        - label: 私は、[AWS 行動規範 (Code of Conduct)](https://aws.amazon.com/jp/codeofconduct/) を確認し、同意しました
          required: true
  - type: input
    id: contact
    attributes:
      label: Twitter ID (必須)
      description: Twitter ID (ダイレクトメッセージ可能なもの)をご記入ください。採択後、運営よりダイレクトメッセージにてご連絡します
      placeholder: ここに Twitter ID をご記入ください
    validations:
      required: true
  - type: checkboxes
    id: session-title
    attributes:
      label: セッションタイトル (必須)
      options:
        - label: セッションのタイトルをイシュー件名に最大40文字程度で入力しました
          required: true
  - type: textarea
    id: session-abstract
    attributes:
      label: セッションのアブストラクト (最大250文字) (必須)
      description: 採択の場合、原則としてこのままセッション情報として Web に掲載されます
      placeholder: ここにセッション アブストラクトをご記入ください
    validations:
      required: true
  - type: textarea
    id: session-detail
    attributes:
      label: セッションについての補足情報 (最大800文字) (任意)
      description: セッション内容についてタイトルおよびアブストラクトのみで説明しきれない場合、補足情報を800文字以下にて記入してください
      placeholder: ここにセッションの補足説明をお書きください
    validations:
      required: false
