name: 'Tweet CfP'

on:
  issues:
    types: ['opened']

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tweet 
        uses: snow-actions/tweet@v1.2.0
        env:
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        with:
          status: |
            Issue opened ${{ github.issues.issue.title }}
            ${{ github.issues.issue.html_url }}
      # - name: Tweet details
      #   uses: snow-actions/tweet@v1.2.0
      #   with:
      #     status: |
      #       Additional information
      #     in_reply_to_status_id: ${{ fromJSON(steps.summary.outputs.response).id_str }}